coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080

# === ОТКЛЮЧАЕМ АУТЕНТИФИКАЦИЮ ===
http-server.authentication.type=INSECURE

# === SHARED SECRET (любая строка) ===
internal-communication.shared-secret=some-random-secret-12345

# === ОТКЛЮЧАЕМ WebUI аутентификацию ===
web-ui.enabled=false