sources:
  - name: aushan_silver
    description: "Данные Apache Iceberg"
    schema: aushan_silver
    database: iceberg
    tables:
      - name: sales
        description: 'Данные Ашана, приведенные к одному виду'
        columns: 
        - name: 'year'
          description: 'Год продажи'